CREATE DATABASE data_analysis_project
USE data_analysis_project
SELECT * FROM Customer_behaviour_analysis;

--1 which category generates highest revenue
SELECT
    Category,
    ROUND(SUM(Purchase_Amount),2) AS Highest_Revenue
FROM customer_behaviour_analysis
GROUP BY Category
ORDER BY Highest_Revenue DESC


--2 Are discount actually increasing purchase value

SELECT * FROM Customer_behaviour_analysis
SELECT
   Discount_Applied,
    ROUND(SUM(Purchase_Amount),2) AS Total_Revenue,
    ROUND(AVG(Purchase_Amount), 2) AS Avg_Purchase
    FROM Customer_behaviour_analysis
GROUP BY  Discount_Applied

--Impact 
-- Identify effectiveness of discounts
-- Reduce unneccessary discount costs
-- Improve profit margins

--3 What is the total revenue generated by male and female customer?

SELECT * FROM Customer_behaviour_analysis
SELECT
    Gender,
    ROUND(SUM(Purchase_Amount),2) AS Highest_Revenue
FROM customer_behaviour_analysis
GROUP BY Gender
ORDER BY Highest_Revenue DESC

-- Impact
-- Helps design targetd marketing compaigns
--Improves Customer segementation strategy
--Enhance personalization efforts

--4 Which customer used a discount but still spent more then the average purchase amount?


SELECT * FROM Customer_behaviour_analysis

SELECT TOP 10
      Customer_ID,
      Purchase_Amount,
      Discount_Applied
FROM Customer_behaviour_analysis
WHERE Discount_Applied = 'Yes' AND Purchase_Amount > (SELECT AVG(Purchase_Amount) FROM Customer_behaviour_analysis)

--Impact 
    --Identifies premium discount-sensitive customers
    --Enables targeted discount campaign
    --Improves customer retention and revenue

--5 Which  are the top/bottom 5 products with the highest average review rating.

SELECT * FROM Customer_behaviour_analysis

SELECT TOP 5
    Item_Purchased,
    ROUND(AVG(Review_Rating),2) AS Avg_ratings

    FROM Customer_behaviour_analysis
    GROUP BY Item_Purchased 
    ORDER BY Avg_ratings DESC

    
SELECT * FROM Customer_behaviour_analysis

SELECT TOP 5
    Item_Purchased,
    ROUND(AVG(Review_Rating),2) AS Avg_ratings

    FROM Customer_behaviour_analysis
    GROUP BY Item_Purchased 
    ORDER BY Avg_ratings ASC

    --Impacts
    -- Promotes high-performing products
    --Improves low-rated products
    --Enhance customer exeprience

    --6. Average purchase: standard vs express shipping

   SELECT 
    Shipping_Type,
    COUNT(DISTINCT Customer_ID) AS Order_Placed,
    ROUND(AVG(Purchase_Amount), 2) AS Avg_Purchase,
    ROUND(SUM(Purchase_Amount), 2) AS Revenue
FROM Customer_behaviour_analysis
--WHERE Shipping_Type IN ('Standard', 'Express')
GROUP BY Shipping_Type
ORDER BY Revenue DESC;

--impacts

--helps optimize shiping pricing strategy
--Encourages premium shipping adoption
--Increase average Oder Value

--7. Do subscribed customers spend more? Compare average spend and total revenue between subscribers  and non-subscribers

 SELECT 
     Subscription_Status,
     COUNT(Customer_ID) AS Users,
     ROUND(AVG(Purchase_Amount), 2) AS Avg_Revenue,
     ROUND(SUM(Purchase_Amount), 2) AS Total_Revenue
FROM Customer_behaviour_analysis
GROUP BY Subscription_Status;

--impact
--Validates subsciption model performance
--Improves customer loyalty programs
--Increase customer lifetime Value(CLV)

--8 Top 5 products with highest discount usage %
SELECT TOP 5
      Item_Purchased,
      COUNT(*) AS Total_Num_Of_Times_Sold,
      COUNT(CASE WHEN Discount_Applied = 'Yes' THEN 1 END) AS Number_Of_Times_Sold_When_Discount_Applied,
      ROUND(
            COUNT(CASE WHEN Discount_Applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*),
            2
      ) AS Discount_Percent
FROM Customer_behaviour_analysis
GROUP BY Item_Purchased
ORDER BY Discount_Percent DESC

--Impact 
--Identifies discount-driven products 
--Helps optimize pricing strategy
--Reduces profit margin loss

--9. Segment customer into new, returning and loyal based on their total number of previous purchase
-- and show the count of each segment.

SELECT * FROM Customer_behaviour_analysis
SELECT
    CASE  
        WHEN Previous_Purchases = 0 THEN 'New Customer'
        WHEN Previous_Purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END AS Customer_Segment,
    COUNT(*) AS Customer_Count
FROM Customer_behaviour_analysis
GROUP BY 
    CASE  
        WHEN Previous_Purchases = 0 THEN 'New Customer'
        WHEN Previous_Purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END;

    --impacts

    --Enables personalized marketing
    --Improves retention strategies
    --Increase conversion rates

    --10.What are the top 3 most purchased products within each category?
 WITH CTE AS (
    SELECT 
        Category,
        Item_Purchased,
        COUNT(*) AS Most_Purchased
    FROM Customer_behaviour_analysis
    GROUP BY Category, Item_Purchased
),
Ranked AS (
    SELECT *,
        RANK() OVER (
            PARTITION BY Category 
            ORDER BY Most_Purchased DESC
        ) AS RNK
    FROM CTE
)
SELECT *
FROM Ranked
WHERE RNK <=3;

--impacts
-- Improves product placement & recommendations
-- Helps inventory optimization
-- Increase sales through best-sellers

--11. Are Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT * FROM Customer_behaviour_analysis

SELECT 
    CASE 
        WHEN Previous_Purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END AS Customer_Type,
    Subscription_Status,
    COUNT(*) AS Customer_Count
FROM Customer_behaviour_analysis
GROUP BY 
    CASE 
        WHEN Previous_Purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END,
        Subscription_Status;

    --Impacts 

    -- Improves subscription targeting
    --Increasing conversion to paid programs
    -- Increase customer retention strategy

   --12. What is the revenue contribution of each age group?
    
    SELECT * FROM Customer_behaviour_analysis
     
     SELECT
         CASE 
           WHEN Age BETWEEN 18 AND 25 THEN '18-25'
           WHEN Age BETWEEN 26 AND 35 THEN '26-35'
           WHEN Age BETWEEN 36 AND 50 THEN '36-50'
           ELSE '51+'
END AS Age_Group,
ROUND(SUM(Purchase_Amount),2) AS Total_Revenue
FROM Customer_behaviour_analysis
GROUP BY CASE 
 WHEN Age BETWEEN 18 AND 25 THEN '18-25'
           WHEN Age BETWEEN 26 AND 35 THEN '26-35'
           WHEN Age BETWEEN 36 AND 50 THEN '36-50'
           ELSE '51+'
END 
 ORDER BY Total_Revenue DESC
         
--Impacts 
--Enables age-based targeting
--Enhance marketing efficiency






